[package]
name = "mexicop2p"
version = "1.0.0"
edition = "2024_07"

[dependencies]
starknet = "2.10.1"

[dev-dependencies]
cairo_test = "2.10.1"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "scarb cairo-test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std_deprecated"]